### ISSUE TITLE
是否可以实现淘宝-支付宝-微博自动化，三个app都有芭芭农场

### ISSUE THREAD

**Issue by WuxinBai** [Vincentlz/taojinbi-js#1]

**Comment by maoshengbo** [comment]
启动报错 怎么搞？ 

$ node taojinbi.js
F:\git_project\taojinbi-js-main\taojinbi.js:700
    <drawer id="drawer">
    ^

SyntaxError: Unexpected token <
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by maoshengbo** [comment]
$ node taojinbi.js
F:\git_project\taojinbi-js-main\taojinbi.js:700

^

SyntaxError: Unexpected token <
at Module._compile (internal/modules/cjs/loader.js:723:23)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
at startup (internal/bootstrap/node.js:283:19)

**Comment by weiouyang** [comment]
1.淘金币做任务有时候会卡住
2.无障碍如何设置默认自动使能的呢？
